FROM node:current-slim

WORKDIR /app

COPY . .

CMD ["node", "client.js"]

# FROM node:current-slim

# WORKDIR /app

# COPY . .

# RUN npm init -y
# RUN npm install node-fetch

# EXPOSE 3000

# CMD ["node", "client.js"]