services:
  api:
    build: .
    container_name: node_api_service2
    ports:
      - "3001:3001"   # HTTP/General
      - "50052:50052" # gRPC
      - "8002:8002"  # WebSocket
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to protect container's node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: always
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8086:8080"
    environment:
      SWAGGER_JSON: /api/openapi.yaml
    volumes:
      - ./openapi.yaml:/api/openapi.yaml

  # ws-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.2
  #   container_name: websocket_service2
  #   ports:
  #     - "8002:8002"  # WebSocket
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules # Anonymous volume to protect container's node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=8002
  #   restart: always
